### ISSUE TITLE
Sudden fall of smack plugin

### ISSUE THREAD

**Issue by hdghg** [hdghg/cjbot#21]
org.jivesoftware.smack.XMPPException$StreamErrorException: stream:error (conflict) text: Заменено новым соединением
        at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:222)
        at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
        at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)

**Comment by hdghg** [comment]
Sudden fall of smack side

     08:47:35.035 [d-off-pool-2] ERROR c.p.g.gateway:288 - #error {
      :cause nil
      [{:type org.jivesoftware.smack.SmackException$NotConnectedException
      :via
        :message nil
        :at [org.jivesoftware.smack.XMPPConnection sendPacket XMPPConnection.java 584]}]
      :trace
      [[org.jivesoftware.smack.XMPPConnection sendPacket XMPPConnection.java 584]
       [org.jivesoftware.smackx.muc.MultiUserChat sendMessage MultiUserChat.java 1682]
       [sun.reflect.GeneratedMethodAccessor9 invoke nil -1]
       [java.lang.reflect.Method invoke Method.java 498]
       [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
       [cjbot.plugins.gateway.gateway$start_telegram_gw$fn__3962 invoke gateway.clj 137]
       [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
       [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
       [cjbot.plugins.smack.xmpp_messenger.XmppMessenger send_message xmpp_messenger.clj 49]
       [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
       [clojure.lang.AFn call AFn.java 18]
       [java.util.concurrent.FutureTask run FutureTask.java 266]
       [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
       [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
       [java.lang.Thread run Thread.java 745]]}

**Comment by hdghg** [comment]
first
https://github.com/hdghg/cjbot/commit/3e8e3bf72bac7b418ca0a17d4ceac1fadb37d85b
second
https://github.com/hdghg/cjbot/commit/519f776c7a1af3a84d98d5fa5f5dabb295d462f1
