### ISSUE TITLE
Problem when user with non-printable nickname joins chat

### ISSUE THREAD

**Issue by hdghg** [hdghg/cjbot#26]
19:04:18.018 [d-off-pool-1] ERROR c.p.g.gateway:288 - #error {
     :cause bad-request
     :via
     [{:type org.jivesoftware.smack.XMPPException$XMPPErrorException
       :message bad-request
       :at [org.jivesoftware.smack.PacketCollector nextResultOrThrow PacketCollector.java 196]}]
     :trace
     [[org.jivesoftware.smack.PacketCollector nextResultOrThrow PacketCollector.java 196]
      [org.jivesoftware.smack.PacketCollector nextResultOrThrow PacketCollector.java 175]
      [org.jivesoftware.smack.XMPPConnection bindResourceAndEstablishSession XMPPConnection.java 530]
      [org.jivesoftware.smack.tcp.XMPPTCPConnection login XMPPTCPConnection.java 260]
      [sun.reflect.GeneratedMethodAccessor16 invoke nil -1]
      [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
      [java.lang.reflect.Method invoke Method.java 498]
      [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
      [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
      [cjbot.plugins.smack.xmpp_messenger.XmppMessenger connect xmpp_messenger.clj 28]
      [cjbot.plugins.smack.xmpp_messenger.XmppMessenger join_room xmpp_messenger.clj 33]
      [cjbot.plugins.gateway.gateway$new_smack_reflection invokeStatic gateway.clj 33]
      [cjbot.plugins.gateway.gateway$new_smack_reflection invoke gateway.clj 25]
      [cjbot.plugins.gateway.gateway$start_telegram_gw$fn__1342 invoke gateway.clj 163]
      [clojure.core$binding_conveyor_fn$fn__4676 invoke core.clj 1938]
      [clojure.lang.AFn call AFn.java 18]
      [java.util.concurrent.FutureTask run FutureTask.java 266]
      [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
      [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
      [java.lang.Thread run Thread.java 745]]}
    
    
    
    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1555)
    	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
    java.net.SocketException: Connection closed by remote host
    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    	at org.jivesoftware.smack.tcp.PacketWriter.writePackets(PacketWriter.java:190)
    	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
    java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...request xmlns=\'urn:ietf:params:xml:ns:xmpp-stanzas\'/></error></iq>... @1:749
    	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    19:05:17.017 [ Reader (21)] WARN  o.j.s.XMPPConnection:1193 - Connection closed with error
    	at org.jivesoftware.smack.tcp.PacketWriter$1.run(PacketWriter.java:77)
    19:05:17.017 [ Writer (21)] WARN  o.j.s.t.PacketWriter:193 - Exception writing closing stream element
    	at org.jivesoftware.smack.tcp.PacketWriter.access$000(PacketWriter.java:40)
    	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
    	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
    	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
    	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
    	at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:287)
    	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
    	at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
    	at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)
    
    
    19:06:30.030 [ Writer (21)] WARN  o.j.s.t.PacketWriter:193 - Exception writing closing stream element
    java.net.SocketException: Connection closed by remote host
    	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1555)
    	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
    	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
    	at org.jivesoftware.smack.tcp.PacketWriter.writePackets(PacketWriter.java:190)
    	at org.jivesoftware.smack.tcp.PacketWriter.access$000(PacketWriter.java:40)
    	at org.jivesoftware.smack.tcp.PacketWriter$1.run(PacketWriter.java:77)
    19:06:30.030 [ Reader (21)] WARN  o.j.s.XMPPConnection:1193 - Connection closed with error
    java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...</mechanisms>\n</stream:features>... @8:19
    	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
    	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
    	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
    	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
    	at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:287)
    	at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
    	at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)
    
    
    19:07:44.044 [ Writer (21)] WARN  o.j.s.t.PacketWriter:193 - Exception writing closing stream element
    java.net.SocketException: Connection closed by remote host
    	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1555)
    	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
    	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
    	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
    	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
    	at org.jivesoftware.smack.tcp.PacketWriter.writePackets(PacketWriter.java:190)
    	at org.jivesoftware.smack.tcp.PacketWriter.access$000(PacketWriter.java:40)
    	at org.jivesoftware.smack.tcp.PacketWriter$1.run(PacketWriter.java:77)
    19:07:44.044 [ Reader (21)] WARN  o.j.s.XMPPConnection:1193 - Connection closed with error
    java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...</mechanisms>\n</stream:features>... @8:19
    	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
    	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
    	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
    	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
    	at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:287)
    	at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
    	at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)

**Comment by hdghg** [comment]
Nickname: 🌚

**Comment by hdghg** [comment]
Not the best bugfix but it works atleast https://github.com/hdghg/cjbot/commit/e60e729d235d143ed5d4797c5d15f6a67d138b14
